### PR TITLE
Keysign react payment page

### PR DESCRIPTION
**Pull request by tomijaga**
## **Run the Example App using TSDX React**

TSDX scaffolds your new library inside `/src`, and also sets up a [Parcel-based](https://parceljs.org) playground for it inside `/example`.

The recommended workflow is to run TSDX in one terminal:

```bash
npm i # or yarn to install dependencies
npm start # or yarn start
```

This builds to `/dist` and runs the project in watch mode so any edits you save inside `src` causes a rebuild to `/dist`.

Then run the example inside another:

```bash
cd example
npm i # or yarn to install dependencies
npm start # or yarn start
``` 
 
 ## Features

#### Editable 
[Editable](https://user-images.githubusercontent.com/50385769/140975612-99c2376c-05ab-4e5b-af01-b30d0465cda6.mov)

#### Redirects to chrome extension if the browser doesn't have keysign installed
https://user-images.githubusercontent.com/50385769/140548761-48e9f179-6b4d-4f4c-8390-0f3cad331ea8.mov

#### On Mobile
https://user-images.githubusercontent.com/50385769/140550726-f8d18123-1df7-4bfb-b2d7-e4709133a7b2.mov

### CODE REVIEW

**Comment by mrbusysky** [comment]
It should actually be its own page, not a popup It's just the views made in the Figma are mobile-friendly. So the purchase button should send them to another page. This way the website would be able to listen correctly.

Also can you put in the readme that it's a typescript example?

**Comment by tomijaga** [comment]
Okay, I will make the updates to the component and the readme.

**Comment by mrbusysky** [comment]
@tomijaga please remove your histories

**Comment by tomijaga** [comment]
@mrbusysky I've removed the histories folder

**Comment by mrbusysky** [comment]
LGTM
I Will let you know when we submit.

**Pull request merged**
